# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cluster_gen <- function(x, lx = 1L, y = NULL, ly = NULL, prog = TRUE) {
    .Call('_RTransferEntropy_cluster_gen', PACKAGE = 'RTransferEntropy', x, lx, y, ly, prog)
}

