# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_transition_probabilities <- function(x, lx = 1L) {
    .Call('_RTransferEntropy_calculate_transition_probabilities', PACKAGE = 'RTransferEntropy', x, lx)
}

cluster_gen <- function(x, lx = 1L, y = NULL, ly = NULL, prog = TRUE) {
    .Call('_RTransferEntropy_cluster_gen', PACKAGE = 'RTransferEntropy', x, lx, y, ly, prog)
}

freq_table <- function(x) {
    .Call('_RTransferEntropy_freq_table', PACKAGE = 'RTransferEntropy', x)
}

